version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]  # This should correctly pull in the dependencies defined under 'docs' in pyproject.toml

# Optionally, set environment variables if needed (not necessary for this specific case but useful for other configurations)
env:
  READTHEDOCS: True
