# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      # Read the dependencies from pyproject.toml
      extra_requirements:
        - docs  # If you have a `[project.optional-dependencies.docs]` section in pyproject.toml