[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metaprivBIDS"
version = "0.1.0"
description = "A tool for assessing data privacy in tabular data."


license = {text = "MIT License"}
readme = "README.md"
requires-python = "^3.7"

[project.dependencies]
seaborn = "^0.13.2"
pandas = "^2.2.2"
matplotlib = "^3.9.2"
PySide6 = "^6.7.2"
networkx = "^3.3"
numpy = "^2.1.0"

[project.urls]
homepage = "https://your_project_homepage.com"
repository = "https://github.com/yourusername/metaprivBIDS"




