name: Run PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  
    - name: Install Graphviz system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev pkg-config

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install .

 
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/metaprivBIDS" >> $GITHUB_ENV

    - name: Run tests
      run: |
        python -m pytest --maxfail=1 --disable-warnings
