name: Run PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force Node20 usage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Latest version compatible with Node20

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            graphviz libgraphviz-dev pkg-config \
            r-base r-base-dev  # Install R base and development packages

      - name: Set up Python
        uses: actions/setup-python@v4  # Latest version compatible with Node20
        with:
          python-version: '3.9'

      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install .

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/metaprivBIDS" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m pytest --maxfail=1 --disable-warnings
