name: Run PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force Node20 usage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove conflicting packages
        run: sudo apt-get remove --purge -y pkgconf

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            graphviz libgraphviz-dev pkg-config \
            r-base r-base-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install rpy2
          pip install .

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/metaprivBIDS" >> $GITHUB_ENV

      - name: Configure R environment for rpy2
        run: |
          echo "R_HOME=$(R RHOME)" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/R/bin" >> $GITHUB_ENV

      - name: Verify R installation
        run: |
          R --version
          Rscript -e 'print("R is properly installed and configured.")'

      - name: Run tests
        run: |
          python -m pytest --maxfail=1 --disable-warnings
