name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: metaprivbids
          environment-file: environment.yml
          auto-activate-base: false
      - name: Install Python application with uv
        shell: bash -el {0}
        run: uv pip install -e ".[test]"
      - name: Run tests
        shell: bash -el {0}
        run: python -m pytest -q
